server.port=0

spring.application.name=video-service

application-title=Video service

spring.config.import=configserver:http://localhost:8888/

data.folder=C:/PFE/Bessyessa_back/asset
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=80MB