databaseChangeLog:
  - changeSet:
      id: 1
      author: product-service
      changes:
        - sqlFile:
            path: classpath:db/changelog/sql/brand.sql  # Added classpath prefix
            relativeToChangelogFile: false

  - changeSet:
      id: 2
      author: product-service
      changes:
        - sqlFile:
            path: classpath:db/changelog/sql/product_model.sql  # Added classpath prefix
            relativeToChangelogFile: false

  - changeSet:
      id: 3
      author: product-service
      changes:
        - sqlFile:
            path: classpath:db/changelog/sql/product.sql  # Added classpath prefix
            relativeToChangelogFile: false

  - changeSet:
      id: product-4
      author: product-service
      changes:
        - sqlFile:
            path: classpath:db/changelog/sql/fix-product-type.sql  # Added classpath prefix
            relativeToChangelogFile: false

  - changeSet:
      id: product-5
      author: product-service
      changes:
        - sqlFile:
            path: classpath:db/changelog/sql/price_reservation.sql  # Added classpath prefix
            relativeToChangelogFile: false